{{- if and (not .Values.existingSecret) (gt (len .Values.credentials) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "veecode-devportal-platform.secretName" . }}
  labels:
    {{- include "veecode-devportal-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.credentials }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
