{{- if .Values.createClusterRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "common.names.fullname" . }}-clusterrole
rules:
  # Resources para os plugins de k8s
  - apiGroups:
      - "*"
    resources:
      - configmaps
      - cronjobs
      - daemonsets
      - deployments
      - horizontalpodautoscalers
      - ingressclasses
      - ingresses
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - replicasets
      - services
      - statefulsets
      - resourcequotas
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - core.k8sgpt.ai
    resources:
      - results
    verbs:
      - get
      - list
  - apiGroups:
      - zora.undistro.io
    resources:
      - clusterissues
      - vulnerabilityreports
    verbs:
      - get
      - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "common.names.fullname" . }}-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "common.names.fullname" . }}-clusterrole
subjects:
subjects:
  - kind: ServiceAccount
    name: {{ .Values.upstream.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
{{- end }}
